### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#1]
We should decide a coding style.

I suggest these guides from Airbnb : 
- [ES6](https://github.com/airbnb/javascript)
- [React](https://github.com/airbnb/javascript/tree/master/react)

**Comment by davidLeonardi** [comment]
I've spent a lot of time linting the current code.

The linting settings i had with ESLint were, more or less:

``` json
{
    "rules": {
        "no-console": 0,
        "indent": [
            2,
            "tab"
        ],
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "env": {
        "es6": true,
        "browser": true
    },
    "extends": "eslint:recommended",
    "ecmaFeatures": {
        "jsx": true,
        "experimentalObjectRestSpread": true,
        "modules": true
    },
    "plugins": [
        "react"
    ],
    "globals": {
        "require": true
    }
}
```

**Comment by davidLeonardi** [comment]
Looking at the AirBnb React styleguide it doesn't seem that bad though.
The only thing i find horrible is indentation with spaces, but that's just matter of enforcing linting.

**Comment by davidLeonardi** [comment]
So, does anybody want to suggest a ESLint .rc file ?

I have no problem with the AirBnB styleguide so i'd be cool with that.

**Comment by charpeni** [comment]
@johannhof @jvlobo ?

**Comment by johannhof** [comment]
+1 for AirBnB

**Comment by johannhof** [comment]
That means this jscs config https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json and I would say we just go with the default .eslint config and add more entries by demand/pull request.

**Comment by charpeni** [comment]
Airbnb eslint can be found here : https://github.com/yannickcr/eslint-plugin-react

My `.eslintrc.js` looks like this : 

``` javascript
module.exports = {
  extends: 'airbnb',
  plugins: [
    'react',
  ],
};
```

**Comment by jvlobo** [comment]
I think you guys have more experience than me in that field. I'm not sure how deep I can help with code, but I'm open to help with doc and stuff :)
