### ISSUE TITLE
Update image in readme to show the interaction potential of this module.

### ISSUE THREAD

**Issue by davidLeonardi** [react-native-simple-router-community/react-native-simple-router#10]
The original package had a GIF in its description, but this got lost in the previous fork.
I propose to bring this back. Perhaps we can showcase this a bit better as well, now that we have new features in here?
Proposals?

**Comment by ericraio** [comment]
Are you referring to the twitter example animated gif?

**Comment by davidLeonardi** [comment]
yep

**Comment by charpeni** [comment]
Good idea.

In the other repo, I added a random `headerStyle` color feature on each page. How do you find that?

Maybe we can add random `trans` and `hideNavigationBar` value too on each page changed. For the purpose of see all the features available.

**Comment by davidLeonardi** [comment]
Also a good idea.
Perhaps we should briefly wait until the ExpensiveRoute PR lands, and
showcase that as well. And port the twitter example to ES6. ;) all in one
go.

**Comment by davidLeonardi** [comment]
I've just switched the image back to the original one. This can be improved in the future, but for now it looks better than before.
Also, i don't know how to make such a gif :)
