### ISSUE TITLE
Is it possible to change the titleStyle when switching Route?

### ISSUE THREAD

**Issue by BigPun86** [react-native-simple-router-community/react-native-simple-router#100]
Hey there! I would like to change the titleStyle in one of my nested routes. It works for the headerStyle where i just pass the new backgroundColor to it. But nothing changes when i try the same for titleStyle.

```
this.props.replaceRoute({
    name: 'HOME',
    component: Routes.Dashboard,
    titleStyle: {color: 'red'},
    headerStyle: {backgroundColor: 'green'}
});
```

**Comment by charpeni** [comment]
Hi @BigPun86.

At this time, `titleStyle` is not available outside `<Router>` props. 

Until a pull request is submitted you can use `titleComponent` with style inside `titleProps`.

Thank you for this use case.

**Comment by BigPun86** [comment]
@charpeni thanks
