### ISSUE TITLE
Back Button Android

### ISSUE THREAD

**Issue by CreativeManix** [react-native-simple-router-community/react-native-simple-router#102]
I have latest version from NPM, the back button on android closing the app. Instead of going back to previous route.

I tried to take use latest code from this repo (npm git://)

But toRoute method throws error. 

Does back feature on Android works on 0.8.4?

**Comment by davidLeonardi** [comment]
Works fine on iOS, unfortunately I don't have an android device to test on.

**Comment by charpeni** [comment]
Back button handeling needs to be enabled to work, like below :

``` javascript
<Router
  handleBackAndroid
/>
```

After that, on back pressed if the route stack is empty it will close the app, otherwise it will back to the previous route.

**Comment by CreativeManix** [comment]
Oh Yes, it works Thanks.

**Comment by charpeni** [comment]
Happy coding, I'll close this issue since it's resolved.
