### ISSUE TITLE
this.props.setRightProps caused warning.

### ISSUE THREAD

**Issue by WhatAKitty** [react-native-simple-router-community/react-native-simple-router#108]
Hi,
    It is so strange when I set rightProps in constructor, It gave me warning: "Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.".
    Following is my code:
    `constructor(props) {
        super(props);
        props.setRightProps({
            onFilterClicked: () => {
                this.onFilterClicked();
            },
        });
    }`

```
`static rightCorner(props) {
    return (
        <TouchableWithoutFeedback
            onPress={ props.onFilterClicked }
        >
            <Icon
                styles={ styles.rightCorner }
            >
                <Ionicons name={ 'shuffle' } size={ 20 } color={ '#FFF' } /> 
            </Icon>
        </TouchableWithoutFeedback>
    );
}`
```

**Comment by charpeni** [comment]
Can you verify how you pass props and how you declare rightCorner with `examples/Explorer` and `examples/twitter-example` ? If it still doesn't work, we will take a look at it.

**Comment by charpeni** [comment]
I'll close this issue since you didn't answer, please feel free to reopen if it still there.
