### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by anhldbk** [react-native-simple-router-community/react-native-simple-router#113]
I am confused about setting props for: 
- `Router` objects 
- Objects passed to `this.props.toRoute()`

They're sharing common props. For example:
- `backButtonComponent` ~ `leftCorner`
- `rightCorner`

Don't you think that we should remove such common props from `Router` objects?

**Comment by charpeni** [comment]
`Router` props are a default props of each scene.

Object passed to a function like `toRoute`, `replaceRoute`, etc. override the `Router` props.

##### Usage example :

On all my scene, I want by default a burger menu on my `leftComponent`. Except on X route that I want another fancy button, I can do that with the props that are passed to the function.
