### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#12]
- [x] Material design toolbar
- [x] Back button support

**Comment by ericraio** [comment]
it's working on android for me? What's the issue?

**Comment by davidLeonardi** [comment]
Android specific look and feel would be nice, out of the box. There is at
least one location I can think of where there are no android specific
templates present.

**Comment by charpeni** [comment]
Added back Android support PR #20.

**Comment by charpeni** [comment]
Issue should be open. I updated tasks to add material design.

**Comment by davidLeonardi** [comment]
Didnt see that. Yes material design would be great!

**Comment by ericraio** [comment]
I don't know if it's possible with navigator but it would be nice to actually have the standard android nav bar, where you can set more then one right button

**Comment by charpeni** [comment]
@ericraio Like [twitter-example](https://github.com/react-native-simple-router-community/react-native-simple-router/tree/master/twitter-example) ?

**Comment by davidLeonardi** [comment]
You can set a component with two buttons in rightbutton?

**Comment by ericraio** [comment]
@sethx @charpeni 
Ah brain fart, yes you're right

**Comment by charpeni** [comment]
Updated material design task, partial integration in PR #25.

Unfortunately, at this time react-native doesn't support modification on Android status bar without a package.

**Comment by charpeni** [comment]
Should we add a package like this one (https://github.com/NishanthShankar/react-native-android-statusbar) to support it ? Or wait until react-native support it.

**Comment by charpeni** [comment]
Since react-native 0.20.0-rc1 : 
http://facebook.github.io/react-native/releases/0.20/docs/statusbar.html#content

**Comment by sethx** [comment]
@charpeni : Are you on discord?

**Comment by charpeni** [comment]
@sethx No.

**Comment by sethx** [comment]
i'm taking a look at the deprecation / route issue . 
you mentioned you have added some code, yet i don't see it. 
Shall i just copypaste that snippet into index.js and commit it myself?

**Comment by sethx** [comment]
Discord --> http://www.reactiflux.com/

**Comment by sethx** [comment]
find me as @sethx

**Comment by ericraio** [comment]
:+1:

**Comment by charpeni** [comment]
I close this issue, StatusBar delayed to the next release.
