### ISSUE TITLE
hideNavigationBar  leaves a white empty space at the top

### ISSUE THREAD

**Issue by deresegetachew** [react-native-simple-router-community/react-native-simple-router#13]
when i set hideNavigationBar={true) for our router its not actually hiding the NavBar; and it gives this White Colored rectangle at the top
<img width="372" alt="screen shot 2016-01-28 at 10 39 29 am" src="https://cloud.githubusercontent.com/assets/2713659/12645351/8807ec1a-c5da-11e5-9284-1180cbeec287.png">

**Comment by deresegetachew** [comment]
After inspecting through the code i found in index.js that you have a property defined which is not defined in the documentation; the property to use is **noStatusBar**

and here is the code where your using it 
`var margin;
    if(route.trans) {        
      margin = 0;
    } else if (this.props.hideNavigationBar || route.hideNavigationBar) {
      margin = this.props.noStatusBar ? 0 : 20;
    } else {
      margin = 64;
    }`

Reading the Code actually doesn't make much sense your not actually using hideNavigationBar as the property to hide it with ; I suggest rather than introducing a new **noStatusBar** property you can use **hideNavigationBar** already

the fixed code will look something like this: 

`var margin;
    if(route.trans) {        
      margin = 0;
    } else if (this.props.hideNavigationBar){
      margin = 20;
    } else {
      margin = 64;
    }`

While the issue is corrected or the documentation is updated please use  **noStatusBar= {false}** property to get the desired output

**Comment by deresegetachew** [comment]
FYI we need both `hideNavigationBar={true} noStatusBar={true}`  to get the effect described above!

**Comment by charpeni** [comment]
To completely hide the navigator bar without hiding the status bar, you can use this props :
 `hideNavigationBar` and `trans`

**Comment by davidLeonardi** [comment]
I have a feeling this can be closed as well.
All of this functionality is already implemented.
