### ISSUE TITLE
not work in react native 0.27

### ISSUE THREAD

**Issue by fiattt** [react-native-simple-router-community/react-native-simple-router#138]
i found in react native 0.27

the EventEmitter path change from "react-native/Libraries/vendor/emitter/EventEmitter"  to "react-native/Libraries/EventEmitter/EventEmitter"

**Comment by charpeni** [comment]
Thanks, it will be fixed by #137 tomorrow :)

**Comment by khiemnm** [comment]
Hi Charpeni.
Did you fixed it? 
I still get same issue with react native 0.27

**Comment by fgarci03** [comment]
Yeah, I actually came by this today and found out it's almost fixed :D 

Just waiting for the PR!

**Comment by khiemnm** [comment]
great. i'm waiting it :)

**Comment by saimemre** [comment]
Hello, my react native version is 0.27.2. 
I have a Eventmitter problem. I am waiting it.

Thanks.

**Comment by maluramichael** [comment]
Please merge this PR today.
