### ISSUE TITLE
Header: Back button text wraps

### ISSUE THREAD

**Issue by sprice** [react-native-simple-router-community/react-native-simple-router#144]
I've got an example app as simple as the README in this repo. In both Android and iOS the Back button in the header wraps.
iOS ![ios](https://cloud.githubusercontent.com/assets/165397/16503095/3f50efde-3ec6-11e6-9067-68502d4b4d21.png)
Android ![android](https://cloud.githubusercontent.com/assets/165397/16503098/40d9bade-3ec6-11e6-9a3a-387c312bc878.png)

**Comment by sprice** [comment]
Also, i see in Android the heading text is not centered. I'm going to update my issue heading to reflect that.

**Comment by charpeni** [comment]
Title is not supposed to be centered as defined in the [Material Design Guideline](https://material.google.com/layout/structure.html#structure-app-bar).

**Comment by sprice** [comment]
oh thanks. My bad.

**Comment by ericraio** [comment]
+1 im getting this issue too on a new application, im using an arrow instead though

**Comment by charpeni** [comment]
I'm working on it.
