### ISSUE TITLE
Trouble with sceneConfig

### ISSUE THREAD

**Issue by seanavery** [react-native-simple-router-community/react-native-simple-router#171]
When trying the default `Router` example with a firstRoute and no sceneConfig defined I get the following error: `Cannot read property 'sceneConfig' of undefined` It appears like the default sceneConfig is not working.

If I supply a scene config my route looks like:
```
const route = {
  name: 'market',
  component: Market,
  sceneConfig: Navigator.SceneConfigs.FloatFromRight
}
```

I get the following error: `Navigator is not defined`

**Comment by ItsNoHax** [comment]
Are you importing Navigator?

If yes, are you using the latest React-Native? Because it's been deprecated and you need to import it from somewhere else now.

**Comment by davidLeonardi** [comment]
Closing due to this being an external deps issue
