### ISSUE TITLE
not supported by latest version of react-native

### ISSUE THREAD

**Issue by nardbagel** [react-native-simple-router-community/react-native-simple-router#172]
Seems like this module doesn't work with the latest release of react-native as the eventEmitter module that this module depends on is no longer available in react-native. I could be wrong, but I get the error: "unable to resolve module 'react-native/Libraries/EventEmitter/EventEmitter' etc..."

This is as of React-Native 48.4. A downgrade might be the only way to get this module to play nicely.

**Comment by nardbagel** [comment]
Could pull in another dependency like https://github.com/medikoo/event-emitter, and it might solve the problem.

**Comment by pedrodevoto** [comment]
@bwighthunter having same problem. Care to share how you did solve it?

**Comment by maluramichael** [comment]
See #173 my packager didn't complain anymore
