### ISSUE TITLE
Submit on npm and js.coach

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#2]
- [x] Update `package.json`
- [x] Update `README.md`
- [x] Initial release
- [x] Submit on npm
- [x] Submit on js.coach

**Comment by johannhof** [comment]
I can take care of it

**Comment by johannhof** [comment]
@react-native-simple-router-community/react-native-simple-router I need your npm usernames :)

**Comment by charpeni** [comment]
charpeni

**Comment by davidLeonardi** [comment]
sethx

**Comment by jvlobo** [comment]
jvlobo

**Comment by davidLeonardi** [comment]
Do we still care of submission to react.parts?

**Comment by davidLeonardi** [comment]
@charpeni ?

**Comment by charpeni** [comment]
No need, since js.coach is the new catalog.

I will remove it from task list.

**Comment by charpeni** [comment]
I just tagged version v0.6.0 based on commit c17c7e6 (The current version on npm).

Thanks @johannhof.
