### ISSUE TITLE
Naming collision with fbemitter dependency

### ISSUE THREAD

**Issue by Amunds** [react-native-simple-router-community/react-native-simple-router#21]
When I run `react-native run-android` I get the following error in console:

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/amunds/android-dev/lifter/node_modules/react-native/node_modules/fbjs/package.json collides with /Users/amunds/android-dev/lifter/node_modules/fbemitter/node_modules/fbjs/package.json
```

Using:

```
react-native@0.19.0
npm@2.14.15
react-native-simple-router@0.6.0
```

**Comment by charpeni** [comment]
It seems to happen when multiple versions of native-react are required.

At the moment, it should fix this issue :
`rm -rf node_modules/react-native-simple-router/node_modules/react-native`

We will check it out.

**Comment by Amunds** [comment]
There are no node_modules folder in react-native-simple-router, I'm not familiar with npm packaging, but is there a reason why the fbemitter module is installed to <app>/node_modules and not react-native-simple-router/node_modules?

**Comment by davidLeonardi** [comment]
Related to the discussion going on in the pull request about emitting
events for the swipe events, shall we replace fbemitter?

**Comment by Amunds** [comment]
Seems this is a common problem with React Native, referencing: https://github.com/facebook/react-native/issues/5467

I fixed my issue by adding fbemitter to my apps package.json, deleting node_modules folder and used npm3 to install all the modules again.

**Comment by iplus26** [comment]
@Amunds Not works for me... :sob:

**Comment by miknonny** [comment]
1. 
> npm install react-native-simple-router --save
2. 
> rm -rf node_modules/react-native-simple-router/node_modules/react-native
3. 
 restart the package manager
4. 
> npm install fbemitter --save-dev
You might need to restart the package manager again....

**Comment by miknonny** [comment]
this works for me...

```
npm install react-native-simple-router --save
rm -rf node_modules/react-native-simple-router/node_modules/react-native
npm install fbemitter --save-dev 
```

restart the packager

**Comment by davidLeonardi** [comment]
Removed the fbmitter from the dependencies, so this is no longer a react-native-simple-router issue.
