### ISSUE TITLE
Expensive view

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#27]
@AnNOtis https://github.com/MikaelCarpenter/gb-native-router/pull/57

Any news on that?

**Comment by davidLeonardi** [comment]
bumping to next potential release due to inactivity.

**Comment by ericraio** [comment]
That PR has a lot of unnecessary changes irrelevant to the feature it self.

**Comment by davidLeonardi** [comment]
Killing this issue due to inactivity.

Until then, you can simply wrap render-intensive code in :

`InteractionManager.runAfterInteractions(() => {
 //do stuff here
});`
