### ISSUE TITLE
Convert to ES6 style

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#3]
- [x] Convert `README.md` to ES6
- [x] Convert `index.js` and `./components` to ES6
- [x] Convert `./twitter-example` to ES6
- [x] Add `PropTypes` to `index.js` and `./components`

Refer to coding style as defined in #1.

**Comment by ericraio** [comment]
I updated the Readme to ES6 
PR - https://github.com/react-native-simple-router-community/react-native-simple-router/pull/8

**Comment by davidLeonardi** [comment]
Changed status of Readme.md

**Comment by charpeni** [comment]
Updated status of `./twitter-example`.

`index.js` and `./components` are missing propTypes.

**Comment by AnNOtis** [comment]
> index.js and ./components are missing propTypes.

Does anyone work on this? If not, I can work on this.

**Comment by davidLeonardi** [comment]
Go for it.

**Comment by charpeni** [comment]
@AnNOtis Do you work on it or I can do?

**Comment by charpeni** [comment]
Updated status of missing PropTypes.

**Comment by AnNOtis** [comment]
:+1:

**Comment by charpeni** [comment]
Thanks to @ericraio, @sethx and @AnNOtis !
