### ISSUE TITLE
onWillFocus & onDidFocus has been deprecated

### ISSUE THREAD

**Issue by charpeni** [react-native-simple-router-community/react-native-simple-router#30]
`onWillFocus` supplied to `Navigator` has been deprecated. Use `navigationContext.addListener('willfocus', callback)` instead.

`onDidFocus` supplied to `Navigator` has been deprecated. Use `navigationContext.addListener('didfocus', callback)` instead.

Can be related to #15.

**Comment by charpeni** [comment]
I removed this from Navigator component :

``` javascript
onDidFocus={this.onDidFocus}
onWillFocus={this.onWillFocus}
```

I added this in `index.js`

``` javascript
componentDidMount() {
  this.refs.navigator.navigationContext.addListener('willfocus', (event) => {
    const route = event.data.route;
    this.setState({ route });
    this.emitter.emit('willFocus', route.name);
  });

  this.refs.navigator.navigationContext.addListener('didfocus', (event) => {
    const route = event.data.route;
    this.emitter.emit('didFocus', route.name);
  });
}
```

It seems to work, except on the first route, I don't know why.

**Comment by davidLeonardi** [comment]
It seems it's because we still pass onWillFocus as a prop to the navigator. 
Am fixing this now.

**Comment by davidLeonardi** [comment]
@charpeni The first route doesn't get cought because the event listeners are attatched too late. :)

**Comment by davidLeonardi** [comment]
Seems like a chicken and egg problem to me.
The navigationContext is instantiated in Navigator in componentWillMount, which is invoked after the componentWillMount in index.js .
As such, componentWillMount is too early, and componentDidMount is too late to attach the event listeners.
I'm really unsure what do do at this point.

**Comment by davidLeonardi** [comment]
Spent a while investigating options, and have no other ideas.
Will commit more or less what was your code, and we can take on further discussion in the review.

**Comment by davidLeonardi** [comment]
Solved, but i ran into the same caveats as @charpeni , namely that the initial route events don't fire, when the navigator is first instantiated.
They do when one returns to the initial route, so personally I don't see this as much of an impediment.
