### ISSUE TITLE
Unable to install using NPM 3

### ISSUE THREAD

**Issue by CreativeManix** [react-native-simple-router-community/react-native-simple-router#31]
Hi I am unable to install using npm

First I got this error while installing
react-native-simple-router@0.6.0 requires a peer of fbemitter@^2.0.0 but none was installed.

Then I installed fbemitter  (I am not sure if that is correct)

After that I got below error while running the app

Unable to resolve module fbemitter from /Users/.....

Please help

**Comment by davidLeonardi** [comment]
Delete the node_modules/flux/node_modules/fbjs folder manually and be happy.

**Comment by charpeni** [comment]
Unfortunately, it's a react-native issue and not from us.
https://github.com/facebook/react-native/issues/5390#issuecomment-172679236

**Comment by CreativeManix** [comment]
Thanks @charpeni  The link you provided helped lot.

I followed the step you provided, and additionally 

https://github.com/facebook/react-native/issues/5390#issuecomment-178170919 

Everything fixed for now :+1:
