### ISSUE TITLE
On Android NavBar height looks more

### ISSUE THREAD

**Issue by CreativeManix** [react-native-simple-router-community/react-native-simple-router#32]
IOS it is fine, because the device battery,wifi etc.. displayed.

But On Android it looks odd. I try to set height for header but that is hiding the title. Not sure what is the better way to do this. Please help.

**Comment by charpeni** [comment]
Hi @CreativeManix,

I fixed this issue a few days ago, these changes are not available on npm for the moment, it will be deployed on npm with release 0.7.0.

You can use the latest version with `npm install git://github.com/react-native-simple-router/react-native-simple-router.git --save`

**Comment by charpeni** [comment]
I will close this issue, if this doesn't solve your issue please reopen it.

**Comment by CreativeManix** [comment]
Yes Please close. I will test this after the 0.7.0 release.
