### ISSUE TITLE
Cant Hide NAV bar on first page and make it visible on second page

### ISSUE THREAD

**Issue by deresegetachew** [react-native-simple-router-community/react-native-simple-router#33]
The First page we are gone Route to needs to use `<Router />` and the documenation indicates that if we use hideNavigationBar: it Hides the navigation bar, **always** ; What this means is if we hide it on `<Router />` we can never get it back .

Lets assume a use case where this way of doing things can make life very hard:

Splash page with a button that says Register and Signin; we don't want to show a Navbar on the splash page rather we want a picture to fill our view => (user Clikcs Register) => we route the user to Registeration page but we also want the NavBar to be Visible with a backButton so that if the user wants to go to the splash page and click on Signin incase he remembers he had an account.

I have tried a lot of ways  but with no luck; i believe this is a very common use case and we should be able to do it with this router.

**Comment by MosesEsan** [comment]
+1

**Comment by sethx** [comment]
I personally use an empty string as name property on the splash screen...
not ideal, but a fairly decent hack.

I also style the header the same solid color as the background. Note that i
don't use a background image.

But I hear you, it's something that's been nagging me as well.
I just need some time to implement it!

Feel free to contribute a patch if you'd like.

**Comment by charpeni** [comment]
I don't use `hideNavigationBar` on Router component, instead my SplashScreen route contains the following props : `trans` & `hideNavigationBar`.

**Comment by davidLeonardi** [comment]
Closing as @charpeni supplied valid description on how to fix using existing configuration options

**Comment by deresegetachew** [comment]
This Issue Should not be closed! @charpeni  can you give us an example please;
if @charpeni  did it in such a way that : 

define <Router /> index.ios.js and it routes to splash and in splashes componentDidMount method he calls another toRoute to his page with `trans` and `hideNavigationBar` it didnt work for me;

the work around ; which is not a workaround at all is defining something like this with your state variable

```
....
if(this.state.activePage == 'Splash')
render(){return(<Splash />)}
if(this.state.activePage == 'Login')
render(){return(<Router firstRoute={firstRoute} />)}
.....
```

**Comment by davidLeonardi** [comment]
@derese, that's not what @charpeni meant.

```
            <Router
                firstRoute={firstRoute}
                trans={true}
                hideNavigationBar={true}
                noStatusBar={true}
            />
```

Please note the presence of the undocumented noStatusBar option [whoops!]
Will document that now :)

But you want it on a per route level:

```
var auth = {
    name: 'Authentication',
    component: Auth,
    trans: true,
    hideNavigationBar: true,
    noStatusBar: true
};

<Router
    firstRoute={auth}
    headerStyle={style.header}
/>
```

**Comment by deresegetachew** [comment]
@sethx that wouldn't solve the problem; please try a scenario where you have a full page image like a carousel on your first page. that wouldn't solve the problem. What that will do is hide the navigationBar **always** and that is also mentioned in the documentation; the problem is being able to hide it on the first page while being able to make it visible on the follow up pages.

i.e. first page is always the one defined with `<Router />`

**Comment by davidLeonardi** [comment]
@derese please see the updated comment.
does that work?

That configuration is per route.

**Comment by deresegetachew** [comment]
@sethx it works perfectly now thank you!
