### ISSUE TITLE
Deprecation of onWillFocus in Navigator warnings in v0.20 rc1

### ISSUE THREAD

**Issue by davidLeonardi** [react-native-simple-router-community/react-native-simple-router#35]
![screen shot 2016-02-12 at 9 42 14 pm](https://cloud.githubusercontent.com/assets/221954/13019760/83893f38-d1d1-11e5-91de-b2fa92750361.png)

**Comment by charpeni** [comment]
Duplicate of #30.

**Comment by davidLeonardi** [comment]
Damn didnt notice that. sorry!
I hope to find some time to fix this this weekend, and let's make a release then as well.
