### ISSUE TITLE
How to pass parameters to customAction callback methods

### ISSUE THREAD

**Issue by deresegetachew** [react-native-simple-router-community/react-native-simple-router#44]
> customAction: A special callback prop for your action buttons (this can be handy for triggering a side menu for example). The action gets triggered from your custom leftCorner or rightCorner components by calling this.props.customAction("someActionName") from them. It is then picked up like this: `<Router customAction={this.doSomething} />.
> `

thats the documentation it is not mentioned any where how to pass parameters; can we pass parameters ?

**Comment by davidLeonardi** [comment]
It's simply a method that is effectively a callback.

**Comment by deresegetachew** [comment]
@sethx `this.props.customAction("someActionName")` thats how i am calling it and i tried different ways to pass it parameters but wasn't successful;  if possible please drop me a line or two on how to; thats if you have already tried it.

**Comment by davidLeonardi** [comment]
I havent used it in my projects, i'll take a look at it tomorrow.

**Comment by davidLeonardi** [comment]
Glanced over the source code, the options are invoked correctly, i don't see why it doesnt work...

Share some code!

**Comment by deresegetachew** [comment]
```
<Router ...
customAction={this.UserisAuthenticated.bind(this,value)}  ... />
```

......
.......

```
UserisAuthenticated(value)
{
  ....    // when i debug here value is actually holding "UserisAuthenticated"
}

```

///// calling it  //////

`this.props.customAction("UserisAuthenticated",{true});`

**Comment by davidLeonardi** [comment]
have you tried this.props.customAction({.. an object ..}) ? we only pass ONE argument down the line.

**Comment by deresegetachew** [comment]
What about the String parameter we are passing which is the name of our method; i can try with out it; but i guess thats how it identifies the method name the things is the way i see it we can hook up multiple customAction methods to our router and the way to identify one from the other is this name parameter.

**Comment by davidLeonardi** [comment]
Honestly I'm not really sure, was just a shot in the dark.
I'll give it a shot in the next days (not tonight and not tomorrow)

**Comment by deresegetachew** [comment]
@sethx Thank you!

**Comment by davidLeonardi** [comment]
There is indeed nothing special about the arguments passed to customAction. 
It's simply a variable, and assumes no string as a key.
As such, if more complex data structures are to be passed down, simply use an object.
