### ISSUE TITLE
More informative error messages

### ISSUE THREAD

**Issue by liamzebedee** [react-native-simple-router-community/react-native-simple-router#45]
Hey guys, thanks so much for maintaining this library! Filing this as a note (who knows I'll probably implement it later).

Just did a code refactor so that it's in different ES6 modules. Used the wrong import syntax, so one of my components was `undefined`. Got an unhelpful error message like so:

![Imgur](http://i.imgur.com/zw5ow56.png)

Would help to know that the component property was undefined.

**Comment by davidLeonardi** [comment]
I personally don't think that this is a Router issue, it's navigator that's failing on you, not router.

**Comment by liamzebedee** [comment]
Sorry there @sethx - just picked up on that!
