### ISSUE TITLE
Release 0.7.0 and push it out to NPM

### ISSUE THREAD

**Issue by davidLeonardi** [react-native-simple-router-community/react-native-simple-router#46]
Release should be done soon. Possibly today?
@charpeni, @ericraio, @johannhof  what do you say?

**Comment by johannhof** [comment]
Good to go from me. Unfortunately this is one of the things that's harder to sync in a community-project.

So I would say patch (0.7.x) and feature (0.x.0) releases can be published at will and ideally as often as possible. :)

We should also think about what would constitute the library as stable and ready for 1.0, as that would make the whole semver a lot easier.

**Comment by davidLeonardi** [comment]
@johannhof can you plz review the PR's i did ?

Then all that's pending is the stuff that @charpeni is working on for android, but that could land in 0.7.1 when that's done..

I also would agree on pushing out more often to NPM.

**Comment by ericraio** [comment]
man, my notifications were turned off, sorry for the lack of activity.

We should identify a road map for 1.0.0, thoughts?

**Comment by davidLeonardi** [comment]
I'd love to have configuration for routes IN the route itself.
Let me explain: within the route, i'd like the route to set its title, and some other props. This could occur in an early part of the component lifecycle [componentwillmount perhaps] and the API for this would have to be defined somehow.

**Comment by charpeni** [comment]
Good job guys. We are ready to release 0.7.0 !

**Comment by davidLeonardi** [comment]
i fixed the conficts in the branch. someone press the merge button plz

**Comment by charpeni** [comment]
Merged.

I just notice an issue with few breaking lines in the README.

**Comment by davidLeonardi** [comment]
Oh? wanna fix it? I've just deleted old branches here on github.

**Comment by charpeni** [comment]
I do it

**Comment by davidLeonardi** [comment]
-Full conversion to ES6
-Added additional Events, so that router can be used as a central event hub
-Removed breaking dependency on fbjs's fbemitter
-Fixed styling issues
-Restored Android support

wut else?

**Comment by charpeni** [comment]
This seems complete.

**Comment by sethx** [comment]
how to update npm?

**Comment by sethx** [comment]
nvm, in progress.

**Comment by davidLeonardi** [comment]
AAaand it's gone.
https://www.npmjs.com/package/react-native-simple-router

**Comment by davidLeonardi** [comment]
Congrats guys, well done! :dart:
