### ISSUE TITLE
Go forward by swipe left

### ISSUE THREAD

**Issue by jvlobo** [react-native-simple-router-community/react-native-simple-router#5]
Hi there!

I'm trying to load a different view (sending properties as **id**) by swipe from **right to left**

Before achieve this by swipe, I'm trying to load this view with a simple button, but neither I'm be able to do it :/

I got this **index.js**

```
...

var Story = require('./story');

...

goToIndividualStory: function(id){
    this.props.toRoute({
      name: "Story",
      component: Story,
      passProps: { id: id, toRoute: this.props.toRoute },
    });
  },

...

```

And then, in **story.js** is where I'd like to go to another view:

```
...

var Part = require('./part');

...

goToPart: function(id){
    this.props.toRoute({
      name: "Part",
      component: Part,
      passProps: { id: id },
    });
  },

...

```

**Edit:** I also have this to fire the **goToPart** function:

```
...

<TouchableHighlight onPress={ this.goToPart.bind(this, story.next_part) } underlayColor="transparent">
    <Text style={ styles.storyFooterPart }>#24</Text>
</TouchableHighlight>

...

```

I feel like I'm missing something, but I've tried with a lot of different code and I don't achieve it.

I hope you guys can help me out with this.

Thank you :)

**Comment by johannhof** [comment]
What's the problem exactly? Do you get an error message?

**Comment by jvlobo** [comment]
Yes, sorry.

With this code I get this error: http://puu.sh/mE4Ij/446acce939.png

I've edited my first post with more info.

Thanks.

**Comment by johannhof** [comment]
Mmh maybe I'm missing something obvious but I don't see anything wrong, are you sure you're importing/exporting `Story` and `Part` correctly?

**Comment by jvlobo** [comment]
I think so.

**Story** is loading perfect, the problem comes when I try to load **Part** :/

**Comment by davidLeonardi** [comment]
I don't see what could cause this in the router component, as i do more or less the same over and over again.
Perhaps something is wrong in your Part component.
What happens if you substitute story for part in the first call? Does it break immediately?

**Comment by jvlobo** [comment]
Shit... I've just seen the issue... you're right, I had something wrong in my **Part** component...

Thanks a lot :)

**Comment by johannhof** [comment]
:+1:

**Comment by jvlobo** [comment]
Ups, I had forgotten, I asked about how to change to the new view (**Part**) by swiping from right to left of the screen.

Do you guys think this is possible?

Thanks.

**Comment by davidLeonardi** [comment]
For the sake of everyone's information, if you close an issue please detail
what the solution was.

**Comment by jvlobo** [comment]
Sorry.

I've just done differently. Without swiping.

Thanks.
