### ISSUE TITLE
Going back by swiping. Make the area to start swiping bigger.

### ISSUE THREAD

**Issue by jvlobo** [react-native-simple-router-community/react-native-simple-router#50]
Hi there!

<img width="416" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/5671420/13036089/7704ae58-d35e-11e5-9390-f3fb36264773.png">

I'm gonna try to explain it with an image.

Now, when I want to go back in my app with **react-native-simple-router** by swiping, the area where I have to start swiping is really small (light blue in the image). What I'd like to do is to make this area bigger (light blue + dark blue in the image) to be able to start swiping easily.

I don't know if it is possible.

Thanks!

**Comment by davidLeonardi** [comment]
I'm pretty sure this is an iOS specific property, and defined by the
gesture itself, rather than JS logic.

**Comment by jvlobo** [comment]
So do you think it is not possible to change it? 

In Twitter, for example, you can swipe from a bigger area.

Thanks.

**Comment by davidLeonardi** [comment]
@jvlobo seems that sceneconfig can be used to configure gestures, wanna take a look into this?

**Comment by jvlobo** [comment]
Thanks for your answer @sethx 

I've been looking for some info in **React Native** doc but it seems like it doesn't provide so much information about **SceneConfigs**

Do you know how to set properties on that?

Thanks!

**Comment by ericraio** [comment]
You should be able to configure the SceneConfigs directly onto the Navigator, we may need to set some defaults

**Comment by liamzebedee** [comment]
Yeah, if you change the [`edgeHitWidth` variable](https://github.com/facebook/react-native/blob/f48961388e7eb58a52164f7bf9809b5af11e4f43/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L458) to something larger that should fix it.

**Comment by jvlobo** [comment]
Thanks for your help guys.

Should I change the variable directly in **NavigatorSceneConfigs.js** or could I set it in my code?

Thanks.

**Comment by davidLeonardi** [comment]
Set it in your code as a scene config...

**Comment by jvlobo** [comment]
Thank for your help guys.

I've configured a Scene config as it sets here: https://rnplay.org/apps/HPy6UA

The thing is that in the example, they use a **<Navigator>** component. Because I'm using **React Native Simple Router** I set the **configureScene** in my **<Router>** component:

`<Router firstRoute={dashboard} hideNavigationBar={true} noStatusBar={true} configureScene={this._configureScene}/>
`

I don't know if I'm doing something wrong, but it seems like it doesn't work.

Thanks for the help.

**Comment by lucaboieru** [comment]
I have the same issue with the swipe area. I was wondering how can I have my router configured such that it'll have the default iOS start swipe area width. I'm really new to to RN and mobile development and I would really appreciate if you could guide me step-by-step or show me some code.

**Comment by lucaboieru** [comment]
After some troubleshooting i found out how to configure the swipe area width.
I made this function

```
_configureScene() {
    var newConfig = Navigator.SceneConfigs.PushFromRight;
    newConfig.gestures.pop.edgeHitWidth = 50;
    return newConfig;
}
```

and passed it as a prop to the router
`configureScene={this._configureScene()}`

**Comment by jvlobo** [comment]
Hey @lucaboieru 

Have you passed it like this: 

`<Router firstRoute={dashboard} hideNavigationBar={true} noStatusBar={true} configureScene={this._configureScene()}/>
`

I set the `_configureScene()` function above my render function and passed it as a prop but it seems like it doesn't work

**Comment by lucaboieru** [comment]
@jvlobo that's how i passed the new config. You can try setting the `edgeHitWidth` to something like 200 to see clearly if it works or not, because setting it to 50 like i did might seem like it does not work. If that still does not work we'll have to find another solution.

**Comment by jvlobo** [comment]
Yes, I set something like 200 or 300 to test it, but it seems like it doesn't work! :/

This is my code: http://puu.sh/neY0J/16af6f15f2.png

**Comment by lucaboieru** [comment]
You have to call the function `_configureScene` such that it will return to the prop the new configuration to be passed to the Navigator. Notice my `()` at the end. 
![screenshot 2016-02-20 19 18 12](https://cloud.githubusercontent.com/assets/4629087/13198048/f58a521c-d806-11e5-843b-86598610bfe3.png)

**Comment by jvlobo** [comment]
Ok, It was wrong!!

Solved.

Thank you so much :)
