### ISSUE TITLE
Wrap Drawer around Router

### ISSUE THREAD

**Issue by BigPun86** [react-native-simple-router-community/react-native-simple-router#53]
Hey there. I am trying to wrap the react-native-side-menu component around the Router, so it is on top and not under the navBar. I really can´t figure out where the right place is to put it and especially how to pass the Router props down/up to the SideMenu Routes. This was my try:

```
class App extends Component {
  render() {
    return (
        <SideMenu
            menu={<Components.Menu/>}
            isOpen={false}
        >
            <Router
                firstRoute={{
                    name: 'LOGIN',
                    component: Login
                }}
                headerStyle={{
                    backgroundColor: 'black',
                    elevation: 5
                }}
                backButtonComponent={ Components.BackButton }
            />
        </SideMenu>
    );
  }
}
```

Now how can i pass toRoute props to Components.Menu?

**Comment by charpeni** [comment]
I don't know if it's the best answer or if it will work, but you could try using reference.

``` javascript
<Router
  ref={'router'}
  firstRoute={{
    name: 'LOGIN',
    component: Login
  }}
  headerStyle={{
    backgroundColor: 'black',
    elevation: 5
  }}
  backButtonComponent={ Components.BackButton }
/>
```

From `Components.Menu` : 

``` javascript
this.refs.router.props.toRoute();
```

Or by using directly the onForward function : 

``` javascript
 this.refs.router.onForward(route, this.refs.router.refs.navigator);
```

If it doesn't work, let me know I will check it out.

**Comment by ericraio** [comment]
+1 for @charpeni response, you'll want to add a ref to it and `<Components.Menu router={this.ref.router} />`

**Comment by BigPun86** [comment]
I understand what both of you mean, but unfortunately it won´t work...

```
class App extends Component {
  render() {
    return (
        <SideMenu
            menu={<Components.Menu router={this.ref.router} />}
            isOpen={false}
        >
            <Router
                ref={'router'}
                firstRoute={{
                    name: 'LOGIN',
                    component: Login
                }}
                headerStyle={{
                    backgroundColor: 'black',
                    elevation: 5
                }}
                backButtonComponent={ Components.BackButton }
            />
        </SideMenu>
    );
  }
}
```

I might need to dig in to using refs but right now i am getting a undefined is not an object for this.ref.router

**Comment by charpeni** [comment]
this.ref**s**.router

`menu={<Components.Menu router={this.refs.router} />}`

**Comment by BigPun86** [comment]
Upps, okay. Did you get it working or is this just theory? It didn´t work on my App.
1. pass refs router to Menu Component 
   
    router={this.refs.router} 
2. Pass ref='router' to Router Component
   
   ref={'router'}

I get the error "cannot read property of undefined" in the _toRoute function:

```
class Menu extends Component {
_toRoute(name, component) {
    this.refs.router.props.toRoute({
        name,
        component,
    });
}

constructor(props) {
    super(props);
}

render() {
    var header = (
        <View style={styles.logoContainer}>
            <Image style={[styles.logo]} source={require('../../assets/logo.png')}/>
        </View>
    );
.........
```

**Comment by charpeni** [comment]
It's just a theory.

Can you try with this : 

``` javascript
_toRoute(name, component) {
    this.refs.router.onForward({
        name,
        component,
    }, this.refs.router.refs.navigator);
}
```

If it doesn't work, I will take a look this week.

**Comment by BigPun86** [comment]
Okay thanks. Unfortunately its not working -> Cannot read property 'onForward' of undefined
When i debug the App then i have with this.refs an empty object...

**Comment by eljago** [comment]
```
render() {
  return (
    <SideMenu
      menuPosition='right'
      touchToClose={true}
      isOpen={this.state.isOpen}
      disableGestures={true}
      menu={
        <Menu onPress={this._onPress.bind(this)} />
      }
    >
      <Router
        ref={'router'}
        firstRoute={routes.Cinemas}
        headerStyle={styles.header}
        backButtonComponent={BackButton}
        customAction={this._openMenu.bind(this)}
        handleBackAndroid={true}
        rightCorner={MenuButton}
      />
    </SideMenu>
  );
}

_onPress(routeData) {
  this.refs.router.onForward(routeData, this.refs.router.refs.navigator);
}
```

I tried this and the main view animates to the left, with the navigation bar staying in place. Also got the following warning: 

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$scene_0`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by BigPun86** [comment]
Any updates to this?

**Comment by shakdoesgithub** [comment]
I'm also running into this issue, when I slide the side menu from left to right, the navigation bar's background is overlapping the side menu. Image attached
<img width="528" alt="overlap" src="https://cloud.githubusercontent.com/assets/7268367/14228560/d74cbfc4-f8cc-11e5-909e-ef0ae109c4dd.png">

**Comment by BigPun86** [comment]
@shakdoesgithub i ended up using react-native-drawer with type overlay. If you want to have the side menu covering the complete side it is opened then you should add the noStatusBar prop to your router...

**Comment by anhldbk** [comment]
@shakdoesgithub If I swipe the screen from left to right, the router automatically goes back to the previous page. Don't you see that?

**Comment by anhldbk** [comment]
@BigPun86 You made my day!

**Comment by shakdoesgithub** [comment]
@BigPun86 thanks, i'm looking into using that library, but i'm having problems where I can't pass props down to my scenes from the redux store. Are you using redux by any chance?

**Comment by shakdoesgithub** [comment]
@anhldbk when you swipe the side menu does hide. My issue is the side menu doesn't cover up the whole blue background of the nav bar

**Comment by BigPun86** [comment]
@shakdoesgithub yeah i am using redux. i moved the react-native-drawer into a extra js. Then i wraped the drawer around my Router and passed the router a ref. In the drawer component i am doing some weird stuff which actually works. U can catch me at discord for more informations, i can show u then how i solved this explicit Jamal #2918

**Comment by charpeni** [comment]
Still relevant ?

**Comment by BigPun86** [comment]
Nope, should be solved
