### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by kaidenvo** [react-native-simple-router-community/react-native-simple-router#56]
Line 49/50 throwing function not found:

this.onDidFocus = this.onDidFocus.bind(this);
this.onWillFocus = this.onWillFocus.bind(this);

Can this be fixed quickly?

**Comment by charpeni** [comment]
Hi @kaidenvo,

I fixed it in 0.7.1, sorry for the inconvenience.

**Comment by davidLeonardi** [comment]
Sorry for missing this! :(
