### ISSUE TITLE
NavBar components missing on the initial render

### ISSUE THREAD

**Issue by lucaboieru** [react-native-simple-router-community/react-native-simple-router#59]
When I open my app or the twitter-example provided by you the navigation bar is empty until the route is changed and after that everything works just like expected.
![img_1373](https://cloud.githubusercontent.com/assets/4629087/13197605/8631840e-d7fb-11e5-9ec8-782987008f8c.jpg)

Do you have any idea what could cause this?

**Comment by charpeni** [comment]
Thanks for reporting, I confirm this is an issue.

I'm on it.

**Comment by charpeni** [comment]
It's fixed, It will be available in the next release when a community member has accepted my pull request.

**Comment by lucaboieru** [comment]
Thank you very much for the effort and the fast response!

**Comment by BigPun86** [comment]
+1

**Comment by davidLeonardi** [comment]
merged

**Comment by charpeni** [comment]
Available in release v0.7.2.
