### ISSUE TITLE
Configurable width for the navbar title and corner button.

### ISSUE THREAD

**Issue by lucaboieru** [react-native-simple-router-community/react-native-simple-router#66]
In my app I use not only icons, but also text for the corner buttons and something interesting happens. Here's a screenshot:
![screenshot 2016-02-21 15 07 29](https://cloud.githubusercontent.com/assets/4629087/13202719/6a1a3bdc-d8ad-11e5-8512-ba2a207cd2e3.png)

The title overlays the corner button. From my understanding that's because the title container has `flex: 6` [(here)](https://github.com/react-native-simple-router-community/react-native-simple-router/blob/master/components/NavBarContent.js#L206) the corners have `flex: 1` [(here)](https://github.com/react-native-simple-router-community/react-native-simple-router/blob/master/components/NavBarContent.js#L44). If, for example, I set the corner flex to `2` everything works as I want.
Could it be possible to make these rules configurable?

Thank you very much for the great work!

**Comment by charpeni** [comment]
We will consider this.

PRs are welcome :)

**Comment by davidLeonardi** [comment]
This is in progress in #83
