### ISSUE TITLE
Can't 'resetToRoute' from leftCorner component passing the same leftCorner button

### ISSUE THREAD

**Issue by pedrodevoto** [react-native-simple-router-community/react-native-simple-router#71]
I have a project pretty much similar to the Twitter example. It is a ListView that has a button assigned to its leftCorner which takes you to a filter view. When you select the filters you want and apply them, you should be taken back to the ListView, with the filters applied. 

I have tried to `resetToRoute` (passing the filter info with `passProps`, but when I specify the same `leftCorner`, I get:

```
Invariant Violation: Element type is invalid: expected a string 
(for built-in components) or a class/function (for composite 
components) but got: object. Check the render method of ``Navigator`
```

If I don't specify the `leftCorner`, I get taken to the ListView but the filter button disappears. I have also tried `toBack` method, but no porps can be passed with it (I think it would be cool). 

Here is my code, and in the last file I specify the line in which the error is thrown.

**index.android.js**

``` javascript
var HomeView = require('./app/views/HomeView');
var FilterButton = require('./app/ui/buttons/Filters');

var startView = {
  name: 'Home',
  component: HomeView,
  leftCorner: FilterButton,
}

var MyApp = React.createClass({
  render: function() {
    return (
        <Router 
          firstRoute={startView}
          headerStyle={styles.header}
          backButtonComponent={BackButton}
          handleBackAndroid={true}
        />
    );
  }
});

AppRegistry.registerComponent('MyApp', () => MyApp);
```

**Filters.js**

``` javascript
var React = require('react-native');
var FilterView = require('../../views/FiltersView');

var Filters = React.createClass({
  goToFilterPage: function() {
    this.props.toRoute({
      name: "Filtros",
      component: FilterView
    });
  },
  render() {
    return (
      <TouchableHighlight underlayColor="transparent" onPress={this.goToFilterPage}>
        <Image source={Globals.Images.filtro} style={styles.icon} />
      </TouchableHighlight>
    )
  }
});
module.exports = Filters;
```

**FiltersView.js**

``` javascript
var React = require('react-native');
var FilterButton = require('./../ui/buttons/Filters');  <--- This is the line that throws the error
var HomeView = require('./app/views/HomeView');

var FiltersView = React.createClass({
  _applyFilters: function() {
    var filters = this.state.filters;
    this.props.resetToRoute({
      name: "Home",
      component: HomeView,
      leftCorner: FilterButton,
      passProps: {filters:filters}
    });
  },
  render() {
    (...)
  }
});

module.exports = FiltersView;
```

**Comment by charpeni** [comment]
If you use `React.createClass()`, your render function in Filters.js must
be like this `render: function() {}`

Le lun. 22 févr. 2016 22:08, pedrodevoto notifications@github.com a
écrit :

**Comment by johannhof** [comment]
> If you use `React.createClass()`, your render function in Filters.js must be like this `render: function() {}`

That is actually fine, shorthand notation also works for object literals (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions)

@pedrodevoto I find your `FiltersView` component rather suspicious. It doesn't have a render function, is that supposed to be this way?

**Comment by pedrodevoto** [comment]
@johannhof I'm sorry, it does have. It has a few components to make the filtering (lists, text inputs, etc). When you click on "Appy filters", it triggers the `_applyFilters` function. I just simplified the code to what I thought was relevant.

**Comment by davidLeonardi** [comment]
That error is usually thrown when a component is undefined within of a render method.

Can you debug your app and make sure that the components you try to render are indeed always defined to what you expect in the render loop?

**Comment by pedrodevoto** [comment]
@sethx I don't know, because I don't know exactly where the error is being produced. I know it is being thrown in the 6th line of _Filters.js_, whenever I uncomment the 2nd line of _FiltersView.js_. Might it be the reason that both components (Filter and FiltersView) require one another?

**Comment by davidLeonardi** [comment]
If it's an empty object, then it's a symptom of a cyclic dependency, which may be solved by inlining one of the require's at execution time, rather than at a module level.

**Comment by pedrodevoto** [comment]
@sethx solved! These are my new _Filters.js_ and _FiltersView.js_ files.

**Filters.js**

``` javascript
var React = require('react-native');
// var FilterView = require('../../views/FiltersView');    <-- REMOVED FROM HERE

var Filters = React.createClass({
  goToFilterPage: function() {
    this.props.toRoute({
      name: "Filtros",
      component: require('../../views/FiltersView')//    <-- INCLUDED HERE
    });
  },
  render() {
    return (
      <TouchableHighlight underlayColor="transparent" onPress={this.goToFilterPage}>
        <Image source={Globals.Images.filtro} style={styles.icon} />
      </TouchableHighlight>
    )
  }
});
module.exports = Filters;
```

**FilterViews.js**

``` javascript
var React = require('react-native');
// var FilterButton = require('./../ui/buttons/Filters');    <-- REMOVED FROM HERE
var HomeView = require('./app/views/HomeView');

var FiltersView = React.createClass({
  _applyFilters: function() {
    var filters = this.state.filters;
    this.props.resetToRoute({
      name: "Home",
      component: HomeView,
      leftCorner: require('./../ui/buttons/Filters'),//    <-- INCLUDED HERE
      passProps: {filters:filters}
    });
  },
  render() {
    (...)
  }
});

module.exports = FiltersView;
```

Thanks!

**Comment by davidLeonardi** [comment]
Fixed as a module dependency issue rather than a routing component issue.
