### ISSUE TITLE
How can i pop back the route?

### ISSUE THREAD

**Issue by BigPun86** [react-native-simple-router-community/react-native-simple-router#72]
Hey there!

I was wondering how to just pop back a route like the title says. Is it possible to use React.Navigator.pop() or something? In my  app this module is just fabulous, but i coudn´t figure out how to jump...

**Comment by BigPun86** [comment]
Okay got it this working:

```
this.props.toBack({
    component: Components....
})
```

But how can i pop back to previous route without telling him to which component to go (
this.props.navigator.pop())

**Comment by davidLeonardi** [comment]
`this.props.toBack(this.props.navigator);`

**Comment by BigPun86** [comment]
Upps, i use to try this.props.toBack(this.props.navigator.pop());

Thanks!!
