### ISSUE TITLE
Release it! :)

### ISSUE THREAD

**Issue by davidLeonardi** [react-native-simple-router-community/react-native-simple-router#73]
@charpeni can you plz release it to npm? I don't have my laptop with me today.

**Comment by davidLeonardi** [comment]
Also, if people use ^0.7.0 they won't get 0.8.0, but they will get 0.7.3, amirite?
So perhaps we should release 0.7.3 instead of 0.8.0 ?

**Comment by davidLeonardi** [comment]
And it's out.

**Comment by charpeni** [comment]
@sethx 
Sorry for the delay, I was out.

I think we should publish it as 0.8.0 because we added new features. Patch (0.0.X), feature (0.X.0).
http://semver.org/

**Comment by davidLeonardi** [comment]
too late :(
unless we re-release?

**Comment by charpeni** [comment]
I think we should do that

**Comment by davidLeonardi** [comment]
Go for it then.

**Comment by charpeni** [comment]
v0.7.3 is unpublished.
v0.8.0 is published.
