### ISSUE TITLE
is titleProps working for anyone ?

### ISSUE THREAD

**Issue by deresegetachew** [react-native-simple-router-community/react-native-simple-router#75]
is titleProps working for anyone ?
i am assuming titleProps is working like passProps;
this is my sample code:

`this.props.toRoute({titleComponent:titlecomp,titleProps:{title:"test"},headerStyle:{backgroundColor:'#299CCA'},hideNavigationBar:false,trans:false,noStatusBar:false,component:require('./ContactDetail'),passProps:{data:rowData,callBack:this.deleteContact.bind(this),token:this.props.data.Token }});`

and is this how we are suppose to access it from within our TitleComponent right ?

`this.props.title`  or `this.props.titleProps.title` ; i am using the first one.

**Comment by charpeni** [comment]
You're right, titleProps wasn't working. It's fixed by release v0.8.3. 

`this.props.title` is the right way to access props.
