### ISSUE TITLE
Error calling replaceRoute

### ISSUE THREAD

**Issue by kevando** [react-native-simple-router-community/react-native-simple-router#78]
https://i.imgur.com/sp87ydX.png

I call this.props.toRoute and it works fine but not replaceRoute

**Comment by tristangodfrey** [comment]
Same issue here, on both `0.8.0` and `0.8.1`

**Comment by davidLeonardi** [comment]
What code triggers this?

**Comment by tristangodfrey** [comment]
I use functions that return route objects, this for example:

```
const { replaceRoute } = this.props;
<Button onPress={() => replaceRoute(registerSuccess())} />
```

Is enough to break it for me. The required arguments are exactly the same as for `toRoute` right?

Logging the props does display everything as you would expect it, `replaceRoute` is there and is a function, until it is called at which point it says: `_this3.replaceRoute is not a function`.

**Comment by davidLeonardi** [comment]
The signature is the same, yes. Looking into it.

**Comment by davidLeonardi** [comment]
Fix on its way. Look for a new release within a couple of minutes.

**Comment by davidLeonardi** [comment]
Released 0.8.2 , find it on NPM

**Comment by tristangodfrey** [comment]
Thanks @sethx , remind me to buy you a beer when I'm not broke anymore!

**Comment by davidLeonardi** [comment]
@tristangodfrey if you live in Amsterdam, you can buy me one anytime :beers:

**Comment by kevando** [comment]
Thanks @sethx ! your responsiveness is quite impressive!
