### ISSUE TITLE
How can I handle BackAndroid with react-native-simple-router?  

### ISSUE THREAD

**Issue by anhvn** [react-native-simple-router-community/react-native-simple-router#80]
Hi Developer Team,

I'm writing an application that need call the toBack() in sub screen, and exit app in first screen when press back button in Android phone.

Would you mind helping me some guildline to implement this.

Thank you so much!

**Comment by 3210jr** [comment]
+1

**Comment by cpjolicoeur** [comment]
The README file documentation lists how to do this: `handleBackAndroid` is a boolean prop you give to `<Router />`

**Comment by anhvn** [comment]
@cpjolicoeur I used this but it did not work! :(

```
        return (
            <Router firstRoute={firstRoute} headerStyle={ styles.routerHeader }
                    titleStyle={styles.routerTitle}
                    backButtonComponent={BackButton}
                    handleBackAndroid={true}
            />
        );
```

**Comment by 3210jr** [comment]
@anhvn 
Hey, I just cleaned my cache and it works like a charm!

run `npm clean cahce`
then stop your package manager and run `react-native run-android`

Hope you have the same luck!

**Comment by pedrodevoto** [comment]
Same here. `handleBackAndroid` does not seem to work for me. Any suggestions or anywhere I could take a look? There is nothing in the logs.

**Comment by cpjolicoeur** [comment]
Can you both (@pedrodevoto and @anhvn) describe what _is_ happening a bit more, because the code works fine for the rest of us.  What happens when you have `handleBackAndroid={true}` and then proceed to use the back button in your app navigation?

**Comment by pedrodevoto** [comment]
@cpjolicoeur it just takes me to the home screen and it seems to clear the route stack, because when I reopen it, it appears back at the first route.

**Comment by anhvn** [comment]
@3210jr Thanks, it worked for me!

**Comment by pedrodevoto** [comment]
I was using an outdated version of react-native. Upgraded to 0.20 and works fine!

EDIT: Was using 0.14.2
