### ISSUE TITLE
sceneConfig with swipe, animation

### ISSUE THREAD

**Issue by ChangJoo-Park** [react-native-simple-router-community/react-native-simple-router#84]
I set sceneConfig with Navigator.SceneConfigs.VerticalUpSwipeJump.

in this situation, route to back action is not make sense.

If I swipe left to right, but view is up to down.

**Comment by davidLeonardi** [comment]
I'm really not sure what you're suggesting here.
The router does not know about the sceneconfig setting... 
Also, gesture handlers come from navigator itself, and as you are overriding animation behaviour, i'd suggest you override gesture behaviour as well.

See #50 for some gesture related information, but in the end, you're customizing behaviour, so you should customize it all the way.
