### ISSUE TITLE
`onWillFocus` supplied to `Navigator` has been deprecated.

### ISSUE THREAD

**Issue by anhvn** [react-native-simple-router-community/react-native-simple-router#85]
Hi,

I'm using react-native: 0.20.0 and I see the warning like this. Does it affect the application? Can I ignore this?

<img width="465" alt="screen shot 2016-03-01 at 1 00 02 pm" src="https://cloud.githubusercontent.com/assets/4526322/13419078/1b26c5d8-dfae-11e5-8b9d-596b6c32328f.png">

**Comment by davidLeonardi** [comment]
Please upgrade to the latest version. This has been fixed already
