### ISSUE TITLE
Back button style via prop

### ISSUE THREAD

**Issue by AntonNiklasson** [react-native-simple-router-community/react-native-simple-router#89]
I would like to be able to apply a style to the back button component by giving a style object. Exactly like you can do with `titleStyle`. Something like adding a `backStyle` prop perhaps.

Thoughts on this?

**Comment by davidLeonardi** [comment]
Why not just use a custom component for that?

**Comment by AntonNiklasson** [comment]
In this case I just wanted to change to text color. I saw the `titleStyle` and expected there to be a `backStyle` or something after that.

**Comment by charpeni** [comment]
I'm agree with @sethx, if you want a custom backButton, you should use `backButtonComponent`.

But I can see the use case with text color, PRs are welcome :)

**Comment by AntonNiklasson** [comment]
I get that. Might submit PR some other day. Closing.
