### ISSUE TITLE
Use Route ID Instead of Name

### ISSUE THREAD

**Issue by reergymerej** [react-native-simple-router-community/react-native-simple-router#90]
It would be nice to use an ID instead of name to identify routes.  In some cases, you'd want to use the same title for multiple routes.  When observing the `routeEmitter`, you only get the name (aka user-friendly title), so you don't know which route was triggered.

For now, I'm using the `titleComponent` and `titleProps` to separate the name from visible title.  It works, but it's extra cruft.

**Comment by davidLeonardi** [comment]
Feel free to make a PR :)

**Comment by reergymerej** [comment]
@sethx done and done!

I left it open and just included the route in addition to the route name.  This way, existing code won't break and devs can query whatever they want instead of introducing an `id` requirement.

**Comment by davidLeonardi** [comment]
Please refer to discussion ongoing in #91

**Comment by charpeni** [comment]
PR #91 was merged, I'll close thank you @reergymerej.
