### ISSUE TITLE
Question: Tab bar implementation

### ISSUE THREAD

**Issue by tristangodfrey** [react-native-simple-router-community/react-native-simple-router#92]
I'm not quite sure how I should implement a tab bar to allow navigation between a small group of routes.

Should I achieve this by nesting a `Router` inside of the main router? So I'll have a single `tab-router` route, which loads my tab-bar + router component. Or is there a better way of doing this?

**Comment by skizzo** [comment]
@tristangodfrey I tried this approach by creating a Router component inside a View, but I don't know how to access my 2 routers's toRoute() or toBack() functions.. Were you able to work it out?

**Comment by tristangodfrey** [comment]
@skizzo This is roughly how I solved it, just a bunch of snippets but it should give you the general idea

```

//This is how I give my nested routes access to the main router `toRoute` function

const createTabs = (toRoute) => {
  return [{
      route: {
        component: Dashboard,
        name: "Home",
        passProps: {
          onQuizListPress: () => toRoute(quizList),
          onTaskListPress: () => toRoute(taskList),
        },
      },
      iconName: "home",
    }];
}

//This is the container component that holds our tabBar + nested router

class Container extends Component {

  //This is for changing the route of our nested router
  _onTabPress(tab) {
    //This worked for me, don't think I was able to access the default
    //router methods so I used the navigator
    this.refs.router.refs.navigator.replace(tab.route)
  }

  const tabs = createTabs(toRoute);

  render (
     return (
      <View>
        <Router ref="router" />
        <TabBar tabs={tabs} onTabPress={(tab) => this._onTabPress(tab)} />
      </View>
    );
  )

}
```

**Comment by charpeni** [comment]
I will need this feature soon, I'll look it in a few days and I'll be back with a feedback.

Using method of `Navigator` with refs will works, maybe our functions should be accessible too.

Thanks for the snippets @tristangodfrey.

**Comment by cpjolicoeur** [comment]
As a quick "fix" in our fork we just ended up exposing the methods directly: https://github.com/mojotech/react-native-simple-router/commit/7d268d7a5cce137718a5d7cc6695f2c381119925

And in a stripped down for demo our router w/ tabbar follows similarly to your example

```
<View>
  <Router .../>
  <TabBar ... />
</View>
```

**Comment by tristangodfrey** [comment]
Thanks @cpjolicoeur , should we document this approach/add an example or just leave this issue up for reference? Would be happy to contribute if needed.

**Comment by cpjolicoeur** [comment]
we'd want @charpeni and other's opinions on it.  Exposing the methods (or a minimal subset of methods) works fine for us.  I never formally submitted a Pull Request back to the mainline project with those changes as I didn't know if it was something they were interested in.  

But maybe a discussion is in order on it.

**Comment by charpeni** [comment]
I think it's a great idea to expose these methods.

> Would be happy to contribute if needed.

@tristangodfrey It would be appreciate :smiley: 

@sethx Any thoughts?

**Comment by cpjolicoeur** [comment]
I'll submit a PR with our exposing changset for review/discussion.

**Comment by charpeni** [comment]
That was fast!

**Comment by charpeni** [comment]
@tristangodfrey Does the documentation is still in planning?

**Comment by akoshman** [comment]
```
<View>
  <Router .../>
  <TabBar ... />
</View>
```

If I wrap **Router** by **View** then nothing appears on the screen.
Can anyone write some instructions how to do this?
And where do you get **TabBar** component?
Thanks.
