### ISSUE TITLE
Issue with Modules in Webpack / Object Is Not Extensible

### ISSUE THREAD

**Issue by mikehuebner** [react-native-simple-router-community/react-native-simple-router#93]
Hey everyone!

Trying to use this and I'm wondering if I'm doing something wrong. Here is the error I'm getting.

```
ERROR in ./~/react-native-simple-router/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./styles in /Users/NOT_MY_NAME/Workspace/React/react-native-kit/node_modules/react-native-simple-router
 @ ./~/react-native-simple-router/index.js 23:14-33

```

I took a look at Index.js and there is `style.ios.js` and `style.android.js` but it is only requesting `./styles`. Is webpack suppose to figure out if we need ios or android? If so, how do I go about fixing that?

EDIT:
After just hardcoding `ios` to the styles (will change if answer shows) I begin to get this error, wondered what this meant...

```
Cannot define property:__navigatorRouteID, object is not extensible.
getRouteID
Navigator.js @ 79:0 // core Navigator class in react native, is this a react native issue?
```

Update:
Reinstalled, not getting that error with the navigator anymore, but the .ios .android issue is still a thing. Any information on that would be awesome, I cannot seem to figure out why or a solution to it. If anyone needs code of my webpack setup, please let me know.

**Comment by davidLeonardi** [comment]
This is not a router related issue, so closing this to de-clutter.
I suggest you post this on stackoverflow or on the react-native issue tracker.
