### ISSUE TITLE
Nested routers

### ISSUE THREAD

**Issue by skizzo** [react-native-simple-router-community/react-native-simple-router#95]
Hi,
is it possible to nest routers? 

For example, 
1. my **root router** would handle modals but mainly display
2. a component _ScreenWithTabBar_, which itself contains 
1. my **tab router** which is capable to replace routes based on the selected tab, and
2. my _ComponentTabBar_ which shows buttons for the routes in **tab router**

Saving global references to the router objects themselves (via the `ref` property of the <Router/> component and setting a global object `onComponentDidMount()`) doesn't help, since the `toRoute()`or `toBack()` functions can't be called on the Router object itself.
Thanks for any hints.

**Comment by charpeni** [comment]
Can be related to #92 ?

**Comment by skizzo** [comment]
Absolutely, thanks.

**Comment by charpeni** [comment]
I'll close this issue since we have a duplication.
