### ISSUE TITLE
How to run the twitter example?

### ISSUE THREAD

**Issue by ahmed1490** [react-native-simple-router-community/react-native-simple-router#97]
Generally I see this ios/ and android/ folder in examples.

**Comment by charpeni** [comment]
@ahmed1490, please refer to [A more advanced example: Twitter app](https://github.com/react-native-simple-router-community/react-native-simple-router#a-more-advanced-example-twitter-app) section of README.

**Comment by ahmed1490** [comment]
I was wondering if i could run without having another app inited.
